# KDE Kiosk -- System Settings modules hidden in policy mode LOCKED.
[KDE Control Module Restrictions][$i]
kcm_users=false
kcm_sddm=false
kcm_kded=false
kcm_autostart=false
kcm_firewall=false
kcm_networkmanagement=false
kcm_clock=false
kcm_regionandlang=false
kcm_splashscreen=false
kcm_desktoptheme=false
kcm_about-distro=false
